import { useSearchParams } from 'react-router-dom';
import { TaskForm } from '../components/TaskForm';

/**
 * NewTaskPage — renders <TaskForm> in create mode.
 *
 * Reads an optional `?listId=` search parameter so that links of the form
 * `/tasks/new?listId=<id>` (generated by ListPage's "New Task" button) pre-select
 * the correct list in the form.
 *
 * On successful submission TaskForm navigates to /dashboard (its default).
 *
 * Requirements: 2.1, 2.2, 2.3, 2.4, 2.6
 */
function NewTaskPage() {
  const [searchParams] = useSearchParams();
  const listId = searchParams.get('listId') ?? undefined;

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-2xl px-4 py-8 sm:px-6 lg:px-8">
        <h1 className="mb-6 text-2xl font-bold text-gray-900">New Task</h1>
        <div className="rounded-lg bg-white p-6 shadow-sm ring-1 ring-gray-200">
          <TaskForm defaultListId={listId} />
        </div>
      </div>
    </div>
  );
}

export default NewTaskPage;
